import { ModuleManifest, MODULE_IDS, PERMISSIONS } from '@ultratorrent/shared';

const P = PERMISSIONS;

/**
 * Manifests for the public Core + bundled community modules. The private
 * Enterprise overlay injects its own manifests at runtime via the registry's
 * `registerExternal()` hook — these are not declared here.
 */
export const CORE_MANIFESTS: ModuleManifest[] = [
  {
    id: MODULE_IDS.AUTH,
    name: 'Authentication',
    description: 'Login, sessions, refresh-token rotation.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [],
    permissions: [],
    routes: ['/api/auth'],
  },
  {
    id: MODULE_IDS.RBAC,
    name: 'Access control (RBAC)',
    description: 'Roles, permissions, and route guards.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH],
    permissions: [P.ROLES_MANAGE],
  },
  {
    id: MODULE_IDS.ACCOUNT,
    name: 'Account & security',
    description: 'Self-service profile, password, and 2FA.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH],
    routes: ['/api/account'],
    permissions: [],
    settingsSections: ['account'],
    features: ['two_factor'],
  },
  {
    id: MODULE_IDS.USERS,
    name: 'Users',
    description: 'User management and role assignment.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH, MODULE_IDS.RBAC],
    permissions: [P.USERS_VIEW, P.USERS_MANAGE],
    routes: ['/api/users'],
    menu: [{ label: 'Users', path: '/users', icon: 'Users', permission: P.USERS_VIEW }],
  },
  {
    id: MODULE_IDS.ENGINE,
    name: 'Torrent engine',
    description: 'Engine provider abstraction (rTorrent) + registry.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH],
    permissions: [P.SYSTEM_VIEW, P.ENGINES_MANAGE],
    routes: ['/api/engines'],
    schedulerJobs: ['torrent_sync'],
    websocketEvents: ['engine:status', 'stats:update', 'torrents:update'],
  },
  {
    id: MODULE_IDS.DASHBOARD,
    name: 'Dashboard',
    description: 'Aggregated stats and recent activity.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH, MODULE_IDS.ENGINE],
    permissions: [P.TORRENTS_VIEW],
    routes: ['/api/dashboard'],
    menu: [{ label: 'Dashboard', path: '/dashboard', icon: 'LayoutDashboard' }],
  },
  {
    id: MODULE_IDS.TORRENTS,
    name: 'Torrents',
    description: 'Torrent list, detail, lifecycle, bulk actions.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH, MODULE_IDS.ENGINE],
    permissions: [P.TORRENTS_VIEW, P.TORRENTS_ADD, P.TORRENTS_DELETE],
    routes: ['/api/torrents'],
    menu: [{ label: 'Torrents', path: '/torrents', icon: 'ListChecks', permission: P.TORRENTS_VIEW }],
  },
  {
    id: MODULE_IDS.SEARCH,
    name: 'Search',
    description: 'Search persisted torrent snapshots.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH],
    permissions: [P.TORRENTS_VIEW],
    routes: ['/api/search'],
  },
  {
    id: MODULE_IDS.TAXONOMY,
    name: 'Categories & tags',
    description: 'Organise torrents with categories and tags.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH],
    permissions: [P.CATEGORIES_MANAGE, P.TAGS_MANAGE],
    routes: ['/api/categories', '/api/tags'],
  },
  {
    id: MODULE_IDS.RSS,
    name: 'RSS automation',
    description: 'Feeds, ranked match candidates, and the Smart Match Builder.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH, MODULE_IDS.ENGINE],
    permissions: [P.RSS_VIEW, P.RSS_MANAGE],
    routes: ['/api/rss'],
    menu: [{ label: 'RSS', path: '/rss', icon: 'Rss', permission: P.RSS_VIEW }],
    schedulerJobs: ['rss_poll'],
    features: ['smart_match_builder', 'match_preferences'],
  },
  {
    id: MODULE_IDS.AUTOMATION,
    name: 'Automation',
    description: 'Trigger/condition/action rule engine.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH, MODULE_IDS.ENGINE],
    permissions: [P.AUTOMATION_VIEW, P.AUTOMATION_MANAGE],
    routes: ['/api/automation'],
    menu: [{ label: 'Automation', path: '/automation', icon: 'Bot', permission: P.AUTOMATION_VIEW }],
    features: ['visual_rule_builder'],
  },
  {
    id: MODULE_IDS.FILES,
    name: 'File manager',
    description: 'Path-safe browsing and file operations.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH],
    permissions: [P.FILES_VIEW, P.FILES_MANAGE],
    routes: ['/api/files'],
    menu: [{ label: 'Files', path: '/files', icon: 'FolderTree', permission: P.FILES_VIEW }],
  },
  {
    id: MODULE_IDS.NOTIFICATIONS,
    name: 'Notifications',
    description: 'In-app feed + multi-channel fan-out.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH],
    permissions: [P.NOTIFICATIONS_MANAGE],
    routes: ['/api/notifications'],
  },
  {
    id: MODULE_IDS.API_KEYS,
    name: 'API keys',
    description: 'Personal API key issue/list/revoke.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH],
    permissions: [P.APIKEYS_MANAGE],
    routes: ['/api/api-keys'],
  },
  {
    id: MODULE_IDS.AUDIT,
    name: 'Audit log',
    description: 'Append-only audit trail of sensitive actions.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH],
    permissions: [P.AUDIT_VIEW],
    routes: ['/api/audit'],
    menu: [{ label: 'Audit', path: '/audit', icon: 'ShieldCheck', permission: P.AUDIT_VIEW }],
  },
  {
    id: MODULE_IDS.SYSTEM,
    name: 'System health',
    description: 'Liveness/readiness probes and health reporting.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [],
    permissions: [P.SYSTEM_VIEW],
    routes: ['/api/system'],
  },
  {
    id: MODULE_IDS.SETTINGS,
    name: 'Settings',
    description: 'Key/value application settings.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH],
    permissions: [P.SETTINGS_VIEW, P.SETTINGS_MANAGE],
    routes: ['/api/settings'],
    menu: [{ label: 'Settings', path: '/settings', icon: 'Settings', permission: P.SETTINGS_VIEW }],
    settingsSections: ['general', 'security', 'appearance'],
  },
  {
    id: MODULE_IDS.MODULE_REGISTRY,
    name: 'Module registry',
    description: 'Edition/module management and licensing surface.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH, MODULE_IDS.RBAC],
    permissions: [P.MODULES_VIEW, P.MODULES_MANAGE],
    routes: ['/api/modules'],
    menu: [{ label: 'Modules', path: '/modules', icon: 'Boxes', permission: P.MODULES_VIEW }],
    settingsSections: ['modules', 'license'],
  },
];

/** Bundled community module (free, optional, on by default). */
export const COMMUNITY_MANIFESTS: ModuleManifest[] = [
  // The Intelligent Media Renamer was merged into a single Premium module
  // (`media_renamer_pro`, see PREMIUM_MANIFESTS) — libraries + rename + jobs +
  // templates + history under one entitlement. No community media module.
];

/**
 * Premium/Enterprise PLACEHOLDERS. These declare extension points only — the
 * real implementations live in the private Enterprise overlay and are injected
 * at runtime. Under the default CommunityLicenseProvider they appear "locked".
 */
export const PREMIUM_MANIFESTS: ModuleManifest[] = [
  {
    id: MODULE_IDS.MEDIA_RENAMER_PRO,
    name: 'Intelligent Media Renamer',
    description:
      'Rename and organise completed downloads for media servers: libraries, server presets, job-based dry-run/execute with rollback, and naming templates.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH, MODULE_IDS.ENGINE, MODULE_IDS.FILES],
    permissions: [
      P.FILES_VIEW,
      P.FILES_MANAGE,
      P.MEDIA_RENAMER_VIEW,
      P.MEDIA_RENAMER_PREVIEW,
      P.MEDIA_RENAMER_EXECUTE,
      P.MEDIA_RENAMER_ROLLBACK,
      P.MEDIA_RENAMER_MANAGE_TEMPLATES,
    ],
    menu: [{ label: 'Media Renamer', path: '/media', icon: 'Clapperboard', permission: P.MEDIA_RENAMER_VIEW }],
    routes: ['/api/media', '/api/media-renamer'],
    features: ['libraries', 'presets', 'dry_run', 'rollback', 'templates', 'plex', 'jellyfin', 'emby', 'kodi', 'hardlink', 'symlink'],
  },
  {
    id: MODULE_IDS.RELEASE_SCORING,
    name: 'Release Scoring',
    description: 'Explainable 0–100 scoring of RSS releases with reasons, warnings, and a recommendation.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH, MODULE_IDS.RSS],
    permissions: [P.RELEASE_SCORING_VIEW, P.RELEASE_SCORING_MANAGE],
    routes: ['/api/release-scoring'],
  },
  {
    id: MODULE_IDS.MEDIA_ACQUISITION_INTELLIGENCE,
    name: 'Media Acquisition Intelligence',
    description:
      'Decides what media to acquire from library gaps, release quality, duplicate risk, watchlists, acquisition profiles, and automation context — explainable decisions, never direct file operations.',
    tier: 'core',
    enabledByDefault: true,
    // Hard deps must be real, registered module ids. UPLM (licensing layer),
    // Smart Match Builder (an RSS feature), and library intelligence are reused
    // at runtime, not declared as module deps; optional integrations
    // (media_renamer_pro/*_integration/multi_server) are soft (documented).
    dependencies: [
      MODULE_IDS.AUTH,
      MODULE_IDS.RBAC,
      MODULE_IDS.MODULE_REGISTRY,
      MODULE_IDS.AUDIT,
      MODULE_IDS.NOTIFICATIONS,
      MODULE_IDS.SETTINGS,
      MODULE_IDS.RSS,
      MODULE_IDS.AUTOMATION,
      MODULE_IDS.RELEASE_SCORING,
    ],
    permissions: [
      P.MEDIA_ACQUISITION_VIEW,
      P.MEDIA_ACQUISITION_MANAGE_WATCHLIST,
      P.MEDIA_ACQUISITION_MANAGE_PROFILES,
      P.MEDIA_ACQUISITION_EVALUATE,
      P.MEDIA_ACQUISITION_APPROVE,
      P.MEDIA_ACQUISITION_REJECT,
      P.MEDIA_ACQUISITION_OVERRIDE,
      P.MEDIA_ACQUISITION_HISTORY,
      P.MEDIA_ACQUISITION_EXPORT,
      P.MEDIA_ACQUISITION_SETTINGS,
    ],
    menu: [{ label: 'Media Acquisition', path: '/media-acquisition', icon: 'Sparkles', permission: P.MEDIA_ACQUISITION_VIEW }],
    routes: ['/api/media-acquisition'],
    websocketEvents: [
      'media_acquisition.evaluation.created',
      'media_acquisition.evaluation.approved',
      'media_acquisition.evaluation.rejected',
      'media_acquisition.download.recommended',
      'media_acquisition.download.skipped',
      'media_acquisition.approval.required',
      'media_acquisition.watchlist.updated',
      'media_acquisition.recommendation.created',
    ],
    schedulerJobs: ['media_acquisition_rss_sweep', 'media_acquisition_watchlist_sweep', 'media_acquisition_quality_upgrade_sweep'],
    settingsSections: ['media-acquisition'],
    features: [
      'watchlist',
      'acquisition_profiles',
      'need_analysis',
      'download_decisions',
      'approval_queue',
      'quality_upgrades',
      'duplicate_prevention',
      'library_gap_fulfillment',
      'explainable_decisions',
    ],
  },
  // Manifest-only premium placeholders (capability declarations; implemented later).
  {
    id: MODULE_IDS.AI_RELEASE_INTELLIGENCE,
    name: 'AI Release Intelligence',
    description: 'AI-assisted release classification and recommendations (planned).',
    tier: 'premium',
    enabledByDefault: false,
    requiredLicenseModule: MODULE_IDS.AI_RELEASE_INTELLIGENCE,
    dependencies: [MODULE_IDS.RELEASE_SCORING],
    permissions: [],
  },
  {
    id: MODULE_IDS.WORKFLOW_TEMPLATES,
    name: 'Workflow Templates',
    description: 'Reusable automation workflow templates (planned).',
    tier: 'premium',
    enabledByDefault: false,
    requiredLicenseModule: MODULE_IDS.WORKFLOW_TEMPLATES,
    dependencies: [MODULE_IDS.AUTOMATION],
    permissions: [],
  },
];

// Enterprise-tier modules were removed in the single-tier community refactor.
export const ENTERPRISE_MANIFESTS: ModuleManifest[] = [];

export const ALL_MANIFESTS: ModuleManifest[] = [
  ...CORE_MANIFESTS,
  ...COMMUNITY_MANIFESTS,
  ...PREMIUM_MANIFESTS,
  ...ENTERPRISE_MANIFESTS,
];
