import { ModuleManifest, MODULE_IDS, PERMISSIONS } from '@ultratorrent/shared';

const P = PERMISSIONS;

/**
 * Manifests for the always-on Core modules. Optional (toggleable) modules live
 * in {@link COMMUNITY_MANIFESTS} below.
 */
export const CORE_MANIFESTS: ModuleManifest[] = [
  {
    id: MODULE_IDS.AUTH,
    name: 'Authentication',
    description: 'Login, sessions, refresh-token rotation.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [],
    permissions: [],
    routes: ['/api/auth'],
  },
  {
    id: MODULE_IDS.RBAC,
    name: 'Access control (RBAC)',
    description: 'Roles, permissions, and route guards.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH],
    permissions: [P.ROLES_MANAGE],
  },
  {
    id: MODULE_IDS.ACCOUNT,
    name: 'Account & security',
    description: 'Self-service profile, password, and 2FA.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH],
    routes: ['/api/account'],
    permissions: [],
    settingsSections: ['account'],
    features: ['two_factor'],
  },
  {
    id: MODULE_IDS.USERS,
    name: 'Users',
    description: 'User management and role assignment.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH, MODULE_IDS.RBAC],
    permissions: [P.USERS_VIEW, P.USERS_MANAGE],
    routes: ['/api/users'],
    menu: [{ label: 'Users', path: '/users', icon: 'Users', permission: P.USERS_VIEW }],
  },
  {
    id: MODULE_IDS.ENGINE,
    name: 'Torrent engine',
    description: 'Engine provider abstraction (rTorrent) + registry.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH],
    permissions: [P.SYSTEM_VIEW, P.ENGINES_MANAGE],
    routes: ['/api/engines'],
    schedulerJobs: ['torrent_sync'],
    websocketEvents: ['engine:status', 'stats:update', 'torrents:update'],
  },
  {
    id: MODULE_IDS.DASHBOARD,
    name: 'Dashboard',
    description: 'Aggregated stats and recent activity.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH, MODULE_IDS.ENGINE],
    permissions: [P.TORRENTS_VIEW],
    routes: ['/api/dashboard'],
    menu: [{ label: 'Dashboard', path: '/dashboard', icon: 'LayoutDashboard' }],
  },
  {
    id: MODULE_IDS.TORRENTS,
    name: 'Torrents',
    description: 'Torrent list, detail, lifecycle, bulk actions.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH, MODULE_IDS.ENGINE],
    permissions: [P.TORRENTS_VIEW, P.TORRENTS_ADD, P.TORRENTS_DELETE],
    routes: ['/api/torrents'],
    menu: [{ label: 'Torrents', path: '/torrents', icon: 'ListChecks', permission: P.TORRENTS_VIEW }],
  },
  {
    id: MODULE_IDS.SEARCH,
    name: 'Search',
    description: 'Search persisted torrent snapshots.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH],
    permissions: [P.TORRENTS_VIEW],
    routes: ['/api/search'],
  },
  {
    id: MODULE_IDS.TAXONOMY,
    name: 'Categories & tags',
    description: 'Organise torrents with categories and tags.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH],
    permissions: [P.CATEGORIES_MANAGE, P.TAGS_MANAGE],
    routes: ['/api/categories', '/api/tags'],
  },
  {
    id: MODULE_IDS.RSS,
    name: 'RSS automation',
    description: 'Feeds, ranked match candidates, and the Smart Match Builder.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH, MODULE_IDS.ENGINE],
    permissions: [P.RSS_VIEW, P.RSS_MANAGE],
    routes: ['/api/rss'],
    menu: [{ label: 'RSS', path: '/rss', icon: 'Rss', permission: P.RSS_VIEW }],
    schedulerJobs: ['rss_poll'],
    features: ['smart_match_builder', 'match_preferences'],
  },
  {
    id: MODULE_IDS.AUTOMATION,
    name: 'Automation',
    description: 'Trigger/condition/action rule engine.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH, MODULE_IDS.ENGINE],
    permissions: [P.AUTOMATION_VIEW, P.AUTOMATION_MANAGE],
    routes: ['/api/automation'],
    menu: [{ label: 'Automation', path: '/automation', icon: 'Bot', permission: P.AUTOMATION_VIEW }],
    features: ['visual_rule_builder'],
  },
  {
    id: MODULE_IDS.FILES,
    name: 'File manager',
    description: 'Path-safe browsing and file operations.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH],
    permissions: [P.FILES_VIEW, P.FILES_MANAGE],
    routes: ['/api/files'],
    menu: [{ label: 'Files', path: '/files', icon: 'FolderTree', permission: P.FILES_VIEW }],
  },
  {
    id: MODULE_IDS.NOTIFICATIONS,
    name: 'Notifications',
    description: 'In-app feed + multi-channel fan-out.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH],
    permissions: [P.NOTIFICATIONS_MANAGE],
    routes: ['/api/notifications'],
  },
  {
    id: MODULE_IDS.API_KEYS,
    name: 'API keys',
    description: 'Personal API key issue/list/revoke.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH],
    permissions: [P.APIKEYS_MANAGE],
    routes: ['/api/api-keys'],
  },
  {
    id: MODULE_IDS.AUDIT,
    name: 'Audit log',
    description: 'Append-only audit trail of sensitive actions.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH],
    permissions: [P.AUDIT_VIEW],
    routes: ['/api/audit'],
    menu: [{ label: 'Audit', path: '/audit', icon: 'ShieldCheck', permission: P.AUDIT_VIEW }],
  },
  {
    id: MODULE_IDS.SYSTEM,
    name: 'System health',
    description: 'Liveness/readiness probes and health reporting.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [],
    permissions: [P.SYSTEM_VIEW],
    routes: ['/api/system'],
  },
  {
    id: MODULE_IDS.SETTINGS,
    name: 'Settings',
    description: 'Key/value application settings.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH],
    permissions: [P.SETTINGS_VIEW, P.SETTINGS_MANAGE],
    routes: ['/api/settings'],
    menu: [{ label: 'Settings', path: '/settings', icon: 'Settings', permission: P.SETTINGS_VIEW }],
    settingsSections: ['general', 'security', 'appearance'],
  },
  {
    id: MODULE_IDS.MODULE_REGISTRY,
    name: 'Module registry',
    description: 'Enable/disable optional modules.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH, MODULE_IDS.RBAC],
    permissions: [P.MODULES_VIEW, P.MODULES_MANAGE],
    routes: ['/api/modules'],
    menu: [{ label: 'Modules', path: '/modules', icon: 'Boxes', permission: P.MODULES_VIEW }],
    settingsSections: ['modules'],
  },
];

/**
 * Optional (toggleable) modules, bundled and on by default. They can be enabled
 * or disabled per install; access to their routes is governed by RBAC.
 */
export const COMMUNITY_MANIFESTS: ModuleManifest[] = [
  {
    id: MODULE_IDS.MEDIA_MANAGER,
    name: 'Media Manager',
    description:
      'Scan, identify, enrich, and organise your media libraries: library scanning, filename identification, metadata/artwork/subtitles, duplicate detection, NFO generation, rename/move for media servers, and a health dashboard.',
    tier: 'community',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH, MODULE_IDS.FILES],
    permissions: [
      P.MEDIA_MANAGER_VIEW,
      P.MEDIA_MANAGER_MANAGE_LIBRARIES,
      P.MEDIA_MANAGER_SCAN,
      P.MEDIA_MANAGER_MATCH,
      P.MEDIA_MANAGER_EDIT_METADATA,
      P.MEDIA_MANAGER_MANAGE_ARTWORK,
      P.MEDIA_MANAGER_MANAGE_SUBTITLES,
      P.MEDIA_MANAGER_RENAME,
      P.MEDIA_MANAGER_MOVE_FILES,
      P.MEDIA_MANAGER_GENERATE_NFO,
      P.MEDIA_MANAGER_MANAGE_INTEGRATIONS,
      P.MEDIA_MANAGER_DELETE,
      P.MEDIA_MANAGER_ADMIN,
      // IMDb metadata provider (compliant dataset / licensed-API).
      P.MEDIA_MANAGER_IMDB_VIEW,
      P.MEDIA_MANAGER_IMDB_CONFIGURE,
      P.MEDIA_MANAGER_IMDB_IMPORT_DATASET,
      P.MEDIA_MANAGER_IMDB_SEARCH,
      P.MEDIA_MANAGER_IMDB_MATCH,
    ],
    menu: [{ label: 'Media', path: '/media', icon: 'Clapperboard', permission: P.MEDIA_MANAGER_VIEW }],
    routes: ['/api/media'],
    features: [
      'libraries',
      'scanning',
      'identification',
      'metadata',
      'artwork',
      'subtitles',
      'duplicates',
      'nfo',
      'rename',
      'presets',
      'plex',
      'jellyfin',
      'emby',
      'kodi',
      'hardlink',
      'symlink',
      'imdb',
    ],
  },
  {
    id: MODULE_IDS.RELEASE_SCORING,
    name: 'Release Scoring',
    description: 'Explainable 0–100 scoring of RSS releases with reasons, warnings, and a recommendation.',
    tier: 'community',
    enabledByDefault: true,
    dependencies: [MODULE_IDS.AUTH, MODULE_IDS.RSS],
    permissions: [P.RELEASE_SCORING_VIEW, P.RELEASE_SCORING_MANAGE],
    routes: ['/api/release-scoring'],
  },
  {
    id: MODULE_IDS.MEDIA_ACQUISITION_INTELLIGENCE,
    name: 'Media Acquisition Intelligence',
    description:
      'Decides what media to acquire from library gaps, release quality, duplicate risk, watchlists, acquisition profiles, and automation context — explainable decisions, never direct file operations.',
    tier: 'community',
    enabledByDefault: true,
    // Hard deps must be real, registered module ids. Smart Match Builder (an RSS
    // feature) and library intelligence are reused at runtime, not declared as
    // module deps.
    dependencies: [
      MODULE_IDS.AUTH,
      MODULE_IDS.RBAC,
      MODULE_IDS.MODULE_REGISTRY,
      MODULE_IDS.AUDIT,
      MODULE_IDS.NOTIFICATIONS,
      MODULE_IDS.SETTINGS,
      MODULE_IDS.RSS,
      MODULE_IDS.AUTOMATION,
      MODULE_IDS.RELEASE_SCORING,
    ],
    permissions: [
      P.MEDIA_ACQUISITION_VIEW,
      P.MEDIA_ACQUISITION_MANAGE_WATCHLIST,
      P.MEDIA_ACQUISITION_MANAGE_PROFILES,
      P.MEDIA_ACQUISITION_EVALUATE,
      P.MEDIA_ACQUISITION_APPROVE,
      P.MEDIA_ACQUISITION_REJECT,
      P.MEDIA_ACQUISITION_OVERRIDE,
      P.MEDIA_ACQUISITION_HISTORY,
      P.MEDIA_ACQUISITION_EXPORT,
      P.MEDIA_ACQUISITION_SETTINGS,
    ],
    menu: [{ label: 'Media Acquisition', path: '/media-acquisition', icon: 'Sparkles', permission: P.MEDIA_ACQUISITION_VIEW }],
    routes: ['/api/media-acquisition'],
    websocketEvents: [
      'media_acquisition.evaluation.created',
      'media_acquisition.evaluation.approved',
      'media_acquisition.evaluation.rejected',
      'media_acquisition.download.recommended',
      'media_acquisition.download.skipped',
      'media_acquisition.approval.required',
      'media_acquisition.watchlist.updated',
      'media_acquisition.recommendation.created',
      'media_acquisition.missing_episodes.scan.progress',
      'media_acquisition.missing_episodes.scan.completed',
      'media_acquisition.download.started',
      'media_acquisition.download.failed',
      'media_acquisition.upgrade.completed',
      'media_acquisition.missing_movies.scan.completed',
      'media_acquisition.waiting',
    ],
    schedulerJobs: ['media_acquisition_rss_sweep', 'media_acquisition_watchlist_sweep', 'media_acquisition_quality_upgrade_sweep'],
    settingsSections: ['media-acquisition'],
    features: [
      'watchlist',
      'acquisition_profiles',
      'need_analysis',
      'download_decisions',
      'approval_queue',
      'quality_upgrades',
      'duplicate_prevention',
      'library_gap_fulfillment',
      'explainable_decisions',
    ],
  },
  {
    id: MODULE_IDS.MEDIA_SERVER_ANALYTICS,
    name: 'Media Server Analytics',
    description:
      'Media server monitoring, analytics, recently-added, watch history, live activity, user/library statistics, scheduled newsletters, and Tautulli analytics import — across Plex, Jellyfin, Emby, and Kodi.',
    tier: 'core',
    enabledByDefault: true,
    dependencies: [
      MODULE_IDS.AUTH,
      MODULE_IDS.RBAC,
      MODULE_IDS.MODULE_REGISTRY,
      MODULE_IDS.AUDIT,
      MODULE_IDS.NOTIFICATIONS,
      MODULE_IDS.SETTINGS,
      MODULE_IDS.MEDIA_MANAGER,
      MODULE_IDS.AUTOMATION,
    ],
    permissions: [
      P.MEDIA_SERVER_ANALYTICS_VIEW,
      P.MEDIA_SERVER_ANALYTICS_MANAGE_CONNECTIONS,
      P.MEDIA_SERVER_ANALYTICS_MANAGE_MAPPINGS,
      P.MEDIA_SERVER_ANALYTICS_VIEW_LIVE_ACTIVITY,
      P.MEDIA_SERVER_ANALYTICS_VIEW_USERS,
      P.MEDIA_SERVER_ANALYTICS_VIEW_HISTORY,
      P.MEDIA_SERVER_ANALYTICS_VIEW_REPORTS,
      P.MEDIA_SERVER_ANALYTICS_MANAGE_NEWSLETTERS,
      P.MEDIA_SERVER_ANALYTICS_SEND_NEWSLETTERS,
      P.MEDIA_SERVER_ANALYTICS_MANAGE_IMPORTS,
      P.MEDIA_SERVER_ANALYTICS_RUN_IMPORTS,
      P.MEDIA_SERVER_ANALYTICS_MANAGE_SETTINGS,
      P.MEDIA_SERVER_ANALYTICS_ADMIN,
    ],
    menu: [
      { label: 'Media Server Analytics', path: '/media-server-analytics', icon: 'MonitorPlay', permission: P.MEDIA_SERVER_ANALYTICS_VIEW },
    ],
    routes: ['/api/media-server-analytics'],
    websocketEvents: [
      'media_server.connection.status',
      'media_server.sync.started',
      'media_server.sync.progress',
      'media_server.sync.completed',
      'media_server.sync.failed',
      'media_server.session.started',
      'media_server.session.updated',
      'media_server.session.ended',
      'media_server.newsletter.generated',
      'media_server.newsletter.sent',
      'media_server.newsletter.failed',
      'media_server.import.started',
      'media_server.import.progress',
      'media_server.import.completed',
      'media_server.import.failed',
      'media_server.import.warning',
      'media_server.import.cancelled',
    ],
    schedulerJobs: ['media_server_session_poll', 'media_server_newsletter_dispatch'],
    settingsSections: ['media-server-analytics'],
    features: ['media_server_connections', 'provider_capabilities', 'server_health', 'multi_server', 'live_activity', 'watch_history', 'analytics_reports', 'tautulli_import', 'newsletters'],
  },
];

export const ALL_MANIFESTS: ModuleManifest[] = [
  ...CORE_MANIFESTS,
  ...COMMUNITY_MANIFESTS,
];
