-- Enable pg_trgm so LIKE/ILIKE on the IMDb catalogue can be index-backed.
--
-- Prisma renders `mode: 'insensitive'` as ILIKE, and ILIKE cannot use a btree
-- index. On the 8.9M-row catalogue that turned every case-insensitive title
-- lookup into a whole-table scan (measured at 47.8s per call on a live host),
-- which saturated Postgres and starved concurrent work.
--
-- The GIN `gin_trgm_ops` indexes themselves are NOT created here. Building them
-- on a fully-imported catalogue takes minutes and `CREATE INDEX` holds a lock, so
-- doing it inside a migration blocks the deploy — and if that build is killed
-- mid-flight Prisma marks the migration failed (P3009) and the app then refuses
-- to start at all (an outage we hit for real).
--
-- Instead `ImdbTrigramIndexService` builds them with CREATE INDEX CONCURRENTLY at
-- runtime, in the background, off the boot path (see that service). CONCURRENTLY
-- cannot run inside a transaction, so it could never live in a migration anyway.
CREATE EXTENSION IF NOT EXISTS pg_trgm;
