package config

import (
	"errors"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"time"

	"github.com/ultratorrent/installer/internal/plan"
	"github.com/ultratorrent/installer/internal/proxy"
)

func testPlan() *plan.Plan {
	p := plan.Recommended("v1.0.0-test")
	p.CreatedAt = time.Date(2026, 1, 2, 3, 4, 5, 0, time.UTC)
	p.Finalize()
	return p
}

func testSecrets() *plan.Secrets {
	return &plan.Secrets{
		PostgresPassword: "PGSENTINELaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
		JWTAccessSecret:  "ACCESSSENTINELbbbbbbbbbbbbbbbbbbbbbbbbbb",
		JWTRefreshSecret: "REFRESHSENTINELcccccccccccccccccccccccc",
		EncryptionKey:    "ENCRYPTSENTINELdddddddddddddddddddddddd",
		AdminPassword:    "ADMINSENTINELeeeeeeee",
	}
}

// --- .env rendering --------------------------------------------------------

func TestEnvSetsEverythingComposeRequires(t *testing.T) {
	/*
	 * docker-compose.yml fails fast on a missing required value via `${VAR:?}`.
	 * Missing one here means the stack refuses to start with a Compose error
	 * rather than an installer error — much harder for an operator to act on.
	 */
	env := RenderEnv(testPlan(), testSecrets())
	values := ParseEnv(env)
	for _, required := range []string{
		"POSTGRES_PASSWORD", "ADMIN_PASSWORD",
		"JWT_ACCESS_SECRET", "JWT_REFRESH_SECRET", "ENCRYPTION_KEY",
	} {
		if values[required] == "" {
			t.Errorf("%s is required by Compose but was not written", required)
		}
	}
}

func TestEnvDoesNotSetDatabaseURL(t *testing.T) {
	// Compose DERIVES DATABASE_URL from POSTGRES_*. Writing our own would
	// override the derivation and drift the moment the user changes a password.
	values := ParseEnv(RenderEnv(testPlan(), testSecrets()))
	if _, present := values["DATABASE_URL"]; present {
		t.Error("DATABASE_URL must be left to Compose to derive")
	}
}

func TestEnvPersistsComposeProfiles(t *testing.T) {
	/*
	 * Docker does not remember `--profile`. Without COMPOSE_PROFILES in .env, a
	 * later plain `docker compose up -d` in this directory STOPS the torrent
	 * engine and every companion — which looks like the application broke.
	 */
	p := testPlan()
	p.Companions.Prowlarr = true
	p.Finalize()
	values := ParseEnv(RenderEnv(p, testSecrets()))
	got := values["COMPOSE_PROFILES"]
	if !strings.Contains(got, "qbittorrent") || !strings.Contains(got, "prowlarr") {
		t.Errorf("COMPOSE_PROFILES = %q, want the selected profiles", got)
	}
}

func TestEnvLeavesSSRFAloneWithBundledProwlarr(t *testing.T) {
	/*
	 * The Compose file already defaults SSRF_ALLOW_HOSTS to `prowlarr`. Writing
	 * our own copy would freeze today's default and silently diverge if the
	 * platform widened it — and the failure is invisible: auto-downloads fail
	 * with a blocked-address error while every container looks healthy.
	 */
	p := testPlan()
	p.Companions.Prowlarr = true
	p.Finalize()
	env := RenderEnv(p, testSecrets())
	if _, present := ParseEnv(env)["SSRF_ALLOW_HOSTS"]; present {
		t.Error("with bundled Prowlarr the installer must not set SSRF_ALLOW_HOSTS")
	}
	// But it must explain why, or the next operator "fixes" the omission.
	if !strings.Contains(env, "SSRF_ALLOW_HOSTS is intentionally not set") {
		t.Error("the omission should be explained in the file")
	}
}

func TestEnvHardensSSRFWithoutProwlarr(t *testing.T) {
	// Explicitly empty, so the Compose default does not trust a `prowlarr` host
	// this deployment does not run.
	env := RenderEnv(testPlan(), testSecrets())
	values := ParseEnv(env)
	value, present := values["SSRF_ALLOW_HOSTS"]
	if !present {
		t.Fatal("without Prowlarr the guard should be set explicitly")
	}
	if value != "" {
		t.Errorf("SSRF_ALLOW_HOSTS = %q, want empty", value)
	}
}

func TestEnvOnlyMentionsTheSelectedEngine(t *testing.T) {
	// Settings for an engine that is not deployed are confusing at best and
	// actively misleading when someone later edits one expecting an effect.
	qb := ParseEnv(RenderEnv(testPlan(), testSecrets()))
	if _, present := qb["RT_DHT"]; present {
		t.Error("rTorrent settings should not appear in a qBittorrent install")
	}

	p := testPlan()
	p.Torrent.Engine = plan.EngineRtorrent
	p.Finalize()
	rt := ParseEnv(RenderEnv(p, testSecrets()))
	if _, present := rt["QBITTORRENT_PORT"]; present {
		t.Error("qBittorrent settings should not appear in an rTorrent install")
	}
	if rt["RT_DHT"] != "off" {
		t.Errorf("RT_DHT = %q, want off by default (this build can crash on DHT)", rt["RT_DHT"])
	}
}

func TestEnvHasAGeneratedHeader(t *testing.T) {
	env := RenderEnv(testPlan(), testSecrets())
	if !strings.HasPrefix(env, "# Generated by the UltraTorrent Installer") {
		t.Error("a generated file must say so on its first line")
	}
	if !strings.Contains(env, "v1.0.0-test") {
		t.Error("the header should record which installer version wrote it")
	}
	if !strings.Contains(env, "reconfigure") {
		t.Error("the header should warn that manual edits may be overwritten")
	}
}

// --- re-run safety ---------------------------------------------------------

func TestExistingSecretsArePreserved(t *testing.T) {
	/*
	 * The single most destructive thing a re-run could do. Regenerating secrets
	 * against a live deployment breaks it quietly: the database password stops
	 * matching the volume that already exists, every session is invalidated, and
	 * a changed ENCRYPTION_KEY makes every stored two-factor secret
	 * undecryptable — with no way back.
	 */
	original := RenderEnv(testPlan(), testSecrets())
	recovered := ExistingSecrets(original)
	if recovered == nil {
		t.Fatal("secrets written by this installer must be readable back")
	}
	want := testSecrets()
	if recovered.PostgresPassword != want.PostgresPassword ||
		recovered.JWTAccessSecret != want.JWTAccessSecret ||
		recovered.EncryptionKey != want.EncryptionKey ||
		recovered.JWTRefreshSecret != want.JWTRefreshSecret {
		t.Error("recovered secrets do not match what was written")
	}
}

func TestExistingSecretsRejectsAnIncompleteFile(t *testing.T) {
	// A file with no signing keys was never a working installation; treating it
	// as one would deploy a stack that cannot boot.
	if got := ExistingSecrets("POSTGRES_PASSWORD=abc\n"); got != nil {
		t.Error("a file missing the JWT secrets must not be treated as usable")
	}
	if got := ExistingSecrets(""); got != nil {
		t.Error("an empty file must not be treated as usable")
	}
}

func TestParseEnvHandlesHandEditedFiles(t *testing.T) {
	// This file may have been edited by hand before the installer ever saw it.
	values := ParseEnv(`
# a comment
export QUOTED="value with spaces"
SINGLE='single quoted'
  SPACED   =   trimmed
EMPTY=
malformed line with no equals
`)
	if values["QUOTED"] != "value with spaces" {
		t.Errorf("QUOTED = %q", values["QUOTED"])
	}
	if values["SINGLE"] != "single quoted" {
		t.Errorf("SINGLE = %q", values["SINGLE"])
	}
	if values["SPACED"] != "trimmed" {
		t.Errorf("SPACED = %q", values["SPACED"])
	}
	if _, present := values["EMPTY"]; !present {
		t.Error("an empty value is still a set variable")
	}
}

// --- override rendering ----------------------------------------------------

func TestNoOverrideWhenNothingNeedsSpecialising(t *testing.T) {
	/*
	 * Compose merges any override it finds, so an empty-but-present file is not
	 * the same as no file. An installation that specialises nothing should leave
	 * `docker compose config` showing exactly the canonical stack.
	 *
	 * A bundled qBittorrent always needs one now — its config volume is bound so
	 * the installer can seed a password into it — so the case to check is an
	 * engine the installer does not configure.
	 */
	p := testPlan()
	p.Torrent.Engine = plan.EngineExternal
	p.Torrent.ExternalURL = "http://engine.lan:8080"
	p.Finalize()
	if got := RenderOverride(p); got != "" {
		t.Errorf("this plan should need no override, got:\n%s", got)
	}
}

func TestBindStorageRedefinesTheVolumeNotTheMounts(t *testing.T) {
	/*
	 * backend, rtorrent and qbittorrent all mount downloads:/downloads.
	 * Redefining the VOLUME moves all three together; rewriting three separate
	 * mounts would have to be repeated for every service added later, and the
	 * first one forgotten would silently write somewhere else.
	 */
	p := testPlan()
	p.Storage.Mode = plan.StorageBind
	p.Storage.MediaRoot = "/srv/media"
	p.Finalize()

	got := RenderOverride(p)
	if !strings.Contains(got, "volumes:") || !strings.Contains(got, "downloads:") {
		t.Fatalf("expected a volume redefinition:\n%s", got)
	}
	if !strings.Contains(got, "device: /srv/media") {
		t.Errorf("the host path should be the bind device:\n%s", got)
	}
	// The in-container path must be untouched, or FILE_MANAGER_ROOTS breaks.
	if strings.Contains(got, "/srv/media:/downloads") {
		t.Error("must not rewrite per-service mounts — redefine the volume instead")
	}
}

func TestPUIDAppliesToTheBackendToo(t *testing.T) {
	/*
	 * Ownership is two-sided. PUID/PGID in .env reach the bundled engine, but
	 * the BACKEND writes into the same tree — imports, renames, artwork — as its
	 * own image user. Setting only the engine leaves files the engine cannot
	 * manage, and it surfaces much later as a permission error mid-import.
	 */
	p := testPlan()
	p.Torrent.PUID, p.Torrent.PGID = 997, 997
	p.Finalize()

	got := RenderOverride(p)
	if !strings.Contains(got, `user: "997:997"`) {
		t.Errorf("the backend should run as the media owner:\n%s", got)
	}
}

func TestYAMLPathIsQuotedWhenItNeedsToBe(t *testing.T) {
	// A path is user input reaching a config file.
	cases := map[string]string{
		"/srv/media":       "/srv/media",
		"/srv/my media":    "'/srv/my media'",
		"/srv/media:extra": "'/srv/media:extra'",
		"/srv/media#1":     "'/srv/media#1'",
		"/srv/o'brien":     "'/srv/o''brien'",
		"":                 "''",
	}
	for input, want := range cases {
		if got := yamlPath(input); got != want {
			t.Errorf("yamlPath(%q) = %q, want %q", input, got, want)
		}
	}
}

// --- writing ---------------------------------------------------------------

func TestEnvIsWrittenOwnerOnly(t *testing.T) {
	dir := t.TempDir()
	w := &Writer{Dir: dir}
	files := Render(testPlan(), testSecrets())

	for _, f := range files {
		if _, err := w.Write(f); err != nil {
			t.Fatal(err)
		}
	}
	info, err := os.Stat(filepath.Join(dir, EnvFileName))
	if err != nil {
		t.Fatal(err)
	}
	// This file holds every secret the deployment has.
	if mode := info.Mode().Perm(); mode != 0o600 {
		t.Errorf(".env mode = %#o, want 0600", mode)
	}
}

func TestDryRunWritesNothing(t *testing.T) {
	dir := t.TempDir()
	w := &Writer{Dir: filepath.Join(dir, "install"), DryRun: true}

	if _, err := w.EnsureDir(); err != nil {
		t.Fatal(err)
	}
	for _, f := range Render(testPlan(), testSecrets()) {
		if _, err := w.Write(f); err != nil {
			t.Fatal(err)
		}
	}
	if entries, _ := os.ReadDir(dir); len(entries) != 0 {
		t.Errorf("a dry run created files: %v", entries)
	}
}

func TestRewritingBacksUpFirst(t *testing.T) {
	dir := t.TempDir()
	w := &Writer{Dir: dir, Now: func() time.Time {
		return time.Date(2026, 1, 2, 3, 4, 5, 0, time.UTC)
	}}
	original := File{Name: "test.env", Mode: ModeSecret, Content: "ORIGINAL=1\n"}
	if _, err := w.Write(original); err != nil {
		t.Fatal(err)
	}

	changed := original
	changed.Content = "CHANGED=1\n"
	actions, err := w.Write(changed)
	if err != nil {
		t.Fatal(err)
	}

	var backup string
	for _, a := range actions {
		if a.Kind == "backup" {
			backup = a.Path
		}
	}
	if backup == "" {
		t.Fatal("replacing a file must back it up first")
	}
	content, err := os.ReadFile(backup)
	if err != nil {
		t.Fatal(err)
	}
	if string(content) != "ORIGINAL=1\n" {
		t.Errorf("the backup should hold the PREVIOUS content, got %q", content)
	}
	// A backup of a secret file must not be more permissive than the original.
	info, _ := os.Stat(backup)
	if mode := info.Mode().Perm(); mode&0o077 != 0 {
		t.Errorf("backup mode = %#o, want no group/other access", mode)
	}
}

func TestIdenticalContentIsNotAChange(t *testing.T) {
	// Re-running with no changes must not churn backups.
	dir := t.TempDir()
	w := &Writer{Dir: dir}
	f := File{Name: "test.env", Mode: ModeSecret, Content: "SAME=1\n"}
	if _, err := w.Write(f); err != nil {
		t.Fatal(err)
	}
	actions, err := w.Write(f)
	if err != nil {
		t.Fatal(err)
	}
	if len(actions) != 1 || actions[0].Kind != "unchanged" {
		t.Errorf("re-writing identical content should be a no-op, got %v", actions)
	}
	entries, _ := os.ReadDir(dir)
	if len(entries) != 1 {
		t.Errorf("a no-op wrote extra files: %v", entries)
	}
}

func TestBackupsInTheSameSecondDoNotCollide(t *testing.T) {
	// Two reconfigures a moment apart; the older backup is the one worth keeping.
	dir := t.TempDir()
	fixed := time.Date(2026, 1, 2, 3, 4, 5, 0, time.UTC)
	w := &Writer{Dir: dir, Now: func() time.Time { return fixed }}

	f := File{Name: "test.env", Mode: ModeSecret, Content: "V=1\n"}
	if _, err := w.Write(f); err != nil {
		t.Fatal(err)
	}
	for i, content := range []string{"V=2\n", "V=3\n"} {
		f.Content = content
		if _, err := w.Write(f); err != nil {
			t.Fatalf("write %d: %v", i, err)
		}
	}
	entries, _ := os.ReadDir(dir)
	backups := 0
	for _, e := range entries {
		if strings.Contains(e.Name(), ".backup-") {
			backups++
		}
	}
	if backups != 2 {
		t.Errorf("expected 2 distinct backups, got %d: %v", backups, entries)
	}
}

func TestActionsNeverContainFileContents(t *testing.T) {
	// A "replace" line for .env must not print what changed.
	dir := t.TempDir()
	w := &Writer{Dir: dir}
	secrets := testSecrets()
	for _, f := range Render(testPlan(), secrets) {
		actions, err := w.Write(f)
		if err != nil {
			t.Fatal(err)
		}
		for _, a := range actions {
			if strings.Contains(a.String(), secrets.JWTAccessSecret) {
				t.Fatalf("an action leaked a secret: %s", a)
			}
		}
	}
}

func TestRedactRemovesSecretsFromText(t *testing.T) {
	s := testSecrets()
	text := "failed to connect: password=" + s.PostgresPassword + " rejected"
	got := Redact(text, s.PostgresPassword, s.JWTAccessSecret)
	if strings.Contains(got, s.PostgresPassword) {
		t.Errorf("redaction failed: %q", got)
	}
	if !strings.Contains(got, "********") {
		t.Errorf("redaction should leave a marker: %q", got)
	}
	// Too short to redact safely — replacing it would mangle unrelated text.
	if got := Redact("a short string", "abc"); got != "a short string" {
		t.Errorf("a very short secret should be left alone, got %q", got)
	}
}

// --- installer state -------------------------------------------------------

func TestStateHoldsNoSecrets(t *testing.T) {
	p := testPlan()
	p.Storage.Mode = plan.StorageBind
	p.Storage.MediaRoot = "/srv/media"
	p.Finalize()

	var b strings.Builder
	if err := WriteState(&b, StateFrom(p, []string{EnvFileName})); err != nil {
		t.Fatal(err)
	}
	out := b.String()
	for _, secret := range []string{
		testSecrets().PostgresPassword, testSecrets().JWTAccessSecret,
		testSecrets().AdminPassword,
	} {
		if strings.Contains(out, secret) {
			t.Fatal("installer state must never contain a secret")
		}
	}
	// It must record enough to describe the deployment.
	if !strings.Contains(out, "/srv/media") || !strings.Contains(out, "qbittorrent") {
		t.Errorf("state should describe the topology:\n%s", out)
	}
}

func TestStateAcceptsANewerSchemaWithAWarning(t *testing.T) {
	/*
	 * The opposite of the plan's rule, deliberately. A plan is an input the user
	 * can regenerate; this describes a deployment that already exists. Refusing
	 * to read it would leave the installer unable to say anything about the very
	 * installation it is standing in.
	 */
	s, warnings, err := ReadState(strings.NewReader(`{"schemaVersion": 99}`))
	if err != nil {
		t.Fatalf("a newer state must still be readable: %v", err)
	}
	if s == nil || len(warnings) == 0 {
		t.Error("a newer schema should be read and warned about")
	}
}

// --- the generated file must match the stack it configures -----------------

// composeVars returns the variables docker-compose.yml interpolates, and the
// subset it marks required with `${VAR:?}`.
func composeVars(t *testing.T) (all, required map[string]bool) {
	t.Helper()
	// Four levels up from internal/config: installer, clients, repo root.
	raw, err := os.ReadFile("../../../../docker-compose.yml")
	if err != nil {
		t.Skipf("docker-compose.yml not reachable from here: %v", err)
	}
	all, required = map[string]bool{}, map[string]bool{}
	// The suffix distinguishes the forms: `${V}`, `${V:-default}`, `${V:?msg}`
	// and `${V?msg}`. Only the last two are required.
	for _, m := range regexp.MustCompile(`\$\{([A-Z_][A-Z0-9_]*)(:?[?}:-])`).
		FindAllStringSubmatch(string(raw), -1) {
		all[m[1]] = true
		if strings.HasSuffix(m[2], "?") {
			required[m[1]] = true
		}
	}
	if len(required) == 0 {
		t.Fatal("parsed no required variables — the regexp has stopped matching")
	}
	return all, required
}

func TestEveryRequiredComposeVarIsGenerated(t *testing.T) {
	// A missing one fails `docker compose up` with a Compose error rather than an
	// installer error, which is far harder for an operator to act on.
	_, required := composeVars(t)
	written := ParseEnv(RenderEnv(testPlan(), testSecrets()))
	for name := range required {
		if written[name] == "" {
			t.Errorf("docker-compose.yml requires %s but the installer does not write it", name)
		}
	}
}

func TestNoGeneratedKeyIsInert(t *testing.T) {
	/*
	 * Caught a real one: PROWLARR_BASE_URL is read by the backend but never
	 * passed into the backend container by docker-compose.yml, so writing it to
	 * .env reached nothing. An operator editing an inert setting sees no effect
	 * and no error — the worst failure mode a config file has.
	 */
	all, _ := composeVars(t)
	// Read by the docker CLI itself rather than interpolated by the file.
	consumedByDocker := map[string]bool{"COMPOSE_PROFILES": true, "COMPOSE_PROJECT_NAME": true}

	p := testPlan()
	p.Companions.Prowlarr = true
	p.Companions.FlareSolverr = true
	p.Torrent.PUID, p.Torrent.PGID = 1000, 1000
	p.Finalize()

	for name := range ParseEnv(RenderEnv(p, testSecrets())) {
		if !all[name] && !consumedByDocker[name] {
			t.Errorf("%s is written to .env but nothing in the stack reads it", name)
		}
	}
}

// --- a timestamp is not a change -------------------------------------------

func TestRegeneratingWithOnlyANewStampIsNotAChange(t *testing.T) {
	/*
	 * The stamp moves on every run by construction. Comparing raw bytes would
	 * make every re-run look like a change — backing up and rewriting `.env`
	 * each time, filling the directory with backups of nothing and burying a
	 * genuine change in the noise, which is exactly when it must be visible.
	 */
	p := testPlan()
	first := RenderEnv(p, testSecrets())

	later := *p
	later.CreatedAt = p.CreatedAt.Add(72 * time.Hour)
	second := RenderEnv(&later, testSecrets())

	if first == second {
		t.Fatal("the two renderings should differ by their stamp, or this proves nothing")
	}
	if !SameGeneratedContent(first, second) {
		t.Error("a moved stamp alone must not count as a change")
	}

	dir := t.TempDir()
	w := &Writer{Dir: dir}
	f := File{Name: EnvFileName, Mode: ModeSecret, Content: first, Secret: true}
	if _, err := w.Write(f); err != nil {
		t.Fatal(err)
	}
	f.Content = second
	actions, err := w.Write(f)
	if err != nil {
		t.Fatal(err)
	}
	if len(actions) != 1 || actions[0].Kind != "unchanged" {
		t.Errorf("re-writing with only a new stamp should be a no-op, got %v", actions)
	}
}

func TestARealChangeIsStillDetectedThroughTheStamp(t *testing.T) {
	// The other half: the stamp-insensitive comparison must not swallow a change
	// that matters.
	p := testPlan()
	first := RenderEnv(p, testSecrets())

	changed := *p
	changed.CreatedAt = p.CreatedAt.Add(time.Hour)
	changed.Networking.FrontendPort = 9999
	changed.Finalize()

	if SameGeneratedContent(first, RenderEnv(&changed, testSecrets())) {
		t.Error("a changed port must be seen as a change")
	}
}

func TestOnlyTheHeaderStampIsIgnored(t *testing.T) {
	// A value further down that happens to start with the same text is content,
	// not a stamp.
	a := "# Generated: monday\nNOTE=# Generated: one\n"
	b := "# Generated: friday\nNOTE=# Generated: two\n"
	if SameGeneratedContent(a, b) {
		t.Error("only the header stamp may be ignored")
	}
}

// --- state carried across runs ---------------------------------------------

func TestInstalledAtSurvivesAReRun(t *testing.T) {
	/*
	 * It is written from time.Now() every run, so without carrying it forward
	 * the first re-run destroys the record of when the installation actually
	 * happened — the one fact nothing else can reconstruct.
	 */
	p := testPlan()
	original := StateFrom(p, []string{EnvFileName})
	original.InstalledAt = time.Date(2020, 5, 6, 7, 8, 9, 0, time.UTC)

	rerun := StateFrom(p, []string{EnvFileName})
	rerun.CarryForward(original)

	if !rerun.InstalledAt.Equal(original.InstalledAt) {
		t.Errorf("installedAt = %v, want the original %v", rerun.InstalledAt, original.InstalledAt)
	}
}

func TestUnchangedStateRendersIdentically(t *testing.T) {
	// So the writer's ordinary "unchanged" path applies and a no-op re-run
	// leaves no backup behind.
	p := testPlan()
	original := StateFrom(p, []string{EnvFileName})
	rerun := StateFrom(p, []string{EnvFileName})
	rerun.UpdatedAt = rerun.UpdatedAt.Add(time.Hour) // a later run
	rerun.CarryForward(original)

	var a, b strings.Builder
	if err := WriteState(&a, original); err != nil {
		t.Fatal(err)
	}
	if err := WriteState(&b, rerun); err != nil {
		t.Fatal(err)
	}
	if a.String() != b.String() {
		t.Errorf("an unchanged deployment should render identical state:\n%s\n--- vs ---\n%s", a.String(), b.String())
	}
}

func TestChangedTopologyMovesUpdatedAt(t *testing.T) {
	p := testPlan()
	original := StateFrom(p, []string{EnvFileName})

	changed := testPlan()
	changed.Companions.FlareSolverr = true
	changed.Companions.Prowlarr = true
	changed.Finalize()

	rerun := StateFrom(changed, []string{EnvFileName})
	rerun.UpdatedAt = rerun.UpdatedAt.Add(time.Hour)
	rerun.CarryForward(original)

	if rerun.SameShape(original) {
		t.Fatal("adding a companion is a change of shape")
	}
	if rerun.UpdatedAt.Equal(original.UpdatedAt) {
		t.Error("a real change must move updatedAt")
	}
	if !rerun.InstalledAt.Equal(original.InstalledAt) {
		t.Error("a real change must still preserve installedAt")
	}
}

func TestSameShapeSeesEveryTopologyField(t *testing.T) {
	/*
	 * Guards the comparison itself. It is written over zeroed copies rather than
	 * field by field so that a field added later is covered automatically — this
	 * test fails if someone replaces it with an explicit list and forgets one,
	 * because the failure mode is invisible: a real change reporting "unchanged".
	 */
	base := StateFrom(testPlan(), []string{EnvFileName})
	mutations := map[string]func(*State){
		"TorrentEngine":    func(s *State) { s.TorrentEngine = "rtorrent" },
		"Profiles":         func(s *State) { s.Profiles = append(s.Profiles, "prowlarr") },
		"Ports":            func(s *State) { s.Ports["frontend"] = 9999 },
		"StorageMode":      func(s *State) { s.StorageMode = "bind" },
		"MediaRoot":        func(s *State) { s.MediaRoot = "/srv/other" },
		"Prowlarr":         func(s *State) { s.Prowlarr = !s.Prowlarr },
		"FlareSolverr":     func(s *State) { s.FlareSolverr = !s.FlareSolverr },
		"BundledProxy":     func(s *State) { s.BundledProxy = !s.BundledProxy },
		"IntakeConfigured": func(s *State) { s.IntakeConfigured = !s.IntakeConfigured },
		"InstallDirectory": func(s *State) { s.InstallDirectory = "/opt/elsewhere" },
		"GeneratedFiles":   func(s *State) { s.GeneratedFiles = nil },
	}
	for name, mutate := range mutations {
		modified := *base
		modified.Ports = map[string]int{}
		for k, v := range base.Ports {
			modified.Ports[k] = v
		}
		modified.Profiles = append([]string(nil), base.Profiles...)
		modified.GeneratedFiles = append([]string(nil), base.GeneratedFiles...)
		mutate(&modified)

		if modified.SameShape(base) {
			t.Errorf("a change to %s was not seen as a change of shape", name)
		}
	}
}

func TestRemoveBacksUpBeforeDeleting(t *testing.T) {
	// A plan that stops needing an override must not leave the old one behind —
	// Compose would keep merging settings the operator has removed.
	dir := t.TempDir()
	w := &Writer{Dir: dir}
	f := File{Name: OverrideFileName, Mode: ModePublic, Content: "services: {}\n"}
	if _, err := w.Write(f); err != nil {
		t.Fatal(err)
	}
	actions, err := w.Remove(OverrideFileName)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, OverrideFileName)); !os.IsNotExist(err) {
		t.Error("the stale override should have been removed")
	}
	var backed bool
	for _, a := range actions {
		if a.Kind == "backup" {
			content, err := os.ReadFile(a.Path)
			if err != nil {
				t.Fatal(err)
			}
			if string(content) != f.Content {
				t.Errorf("backup holds %q", content)
			}
			backed = true
		}
	}
	if !backed {
		t.Error("removing a file must back it up first")
	}
}

func TestRemovingWhatIsNotThereIsNotAnError(t *testing.T) {
	w := &Writer{Dir: t.TempDir()}
	actions, err := w.Remove(OverrideFileName)
	if err != nil {
		t.Fatal(err)
	}
	if len(actions) != 0 {
		t.Errorf("nothing to remove should report nothing, got %v", actions)
	}
}

// --- the bundled engine ----------------------------------------------------

func qbPlan() (*plan.Plan, *plan.Secrets) {
	p := testPlan()
	s := testSecrets()
	s.EnginePassword = "ENGINESENTINELffffffffff"
	return p, s
}

func TestEngineIsSeededSoNoTemporaryPasswordIsEverIssued(t *testing.T) {
	/*
	 * The step this replaces is documented in docker-compose.yml: read a
	 * temporary password out of the container log. That is racy (the line
	 * scrolls away), it puts a live credential into `docker logs` and into
	 * whatever gets pasted into an issue, and it cannot be automated.
	 */
	p, s := qbPlan()
	var config *File
	for i, f := range Render(p, s) {
		if f.Name == EngineConfigFileName {
			config = &Render(p, s)[i]
		}
	}
	if config == nil {
		t.Fatal("no engine config was generated for a bundled qBittorrent")
	}
	if !strings.Contains(config.Content, "Password_PBKDF2") {
		t.Error("the seeded config must set a password")
	}
	if strings.Contains(config.Content, s.EnginePassword) {
		t.Error("the plaintext password must not reach the engine's config")
	}
	if config.Mode != ModeSecret {
		t.Errorf("the engine config holds a verifier; mode = %#o", config.Mode)
	}
	if !config.Once {
		t.Error("qBittorrent rewrites this file itself — the installer must never replace it")
	}
}

func TestNoEngineConfigWithoutABundledEngine(t *testing.T) {
	for _, e := range []plan.Engine{plan.EngineRtorrent, plan.EngineExternal, plan.EngineNone} {
		p, s := qbPlan()
		p.Torrent.Engine = e
		p.Finalize()
		for _, f := range Render(p, s) {
			if f.Name == EngineConfigFileName || f.Name == EngineCredentialsFileName {
				t.Errorf("engine %s should not get a qBittorrent config", e)
			}
		}
	}
}

func TestHostHeaderValidationTracksThePublishedPort(t *testing.T) {
	/*
	 * qBittorrent rejects any request whose Host header names a port other than
	 * its own WebUI port. The Compose file maps ${QBITTORRENT_PORT:-8081}:8080,
	 * so a browser sends `Host: host:8081`, the ports disagree, and every request
	 * — including the login page — comes back 401. Confirmed against qBittorrent
	 * 5.2.3 and against the live deployment, where port 8081 answers 401 while a
	 * Host header naming 8080 answers 200.
	 */
	find := func(p *plan.Plan, s *plan.Secrets) string {
		for _, f := range Render(p, s) {
			if f.Name == EngineConfigFileName {
				return f.Content
			}
		}
		return ""
	}

	p, s := qbPlan()
	p.Torrent.PublishWebUI = true
	p.Torrent.WebUIPort = 8081 // the shipped default: differs from the container port
	p.Finalize()
	if !strings.Contains(find(p, s), "HostHeaderValidation=false") {
		t.Error("a mismatched published port must relax the check, or the UI is unreachable")
	}

	// Not published: nothing outside the Docker network reaches it, and the
	// backend's own Host header already names the matching port.
	p.Torrent.PublishWebUI = false
	p.Finalize()
	if strings.Contains(find(p, s), "HostHeaderValidation") {
		t.Error("with no published UI the check must stay on")
	}

	// Published on the matching port: aligned, so nothing to relax.
	p.Torrent.PublishWebUI = true
	p.Torrent.WebUIPort = QbittorrentContainerPort
	p.Finalize()
	if strings.Contains(find(p, s), "HostHeaderValidation") {
		t.Error("aligned ports need no relaxation")
	}
}

func TestEnginePasswordIsRecoverable(t *testing.T) {
	// The config stores a one-way verifier, so without this the password would
	// exist only in the memory of the process that made it — and the operator
	// could neither sign in nor give UltraTorrent the credentials it needs.
	p, s := qbPlan()
	var creds *File
	files := Render(p, s)
	for i := range files {
		if files[i].Name == EngineCredentialsFileName {
			creds = &files[i]
		}
	}
	if creds == nil {
		t.Fatal("the engine password was not recorded anywhere")
	}
	if !strings.Contains(creds.Content, s.EnginePassword) {
		t.Error("the credentials file should hold the actual password")
	}
	if creds.Mode != ModeSecret {
		t.Errorf("credentials mode = %#o, want 0600", creds.Mode)
	}
	if !creds.Once {
		t.Error("it must never drift from the verifier that was actually seeded")
	}
}

func TestAWriteOnceFileIsNeverReplaced(t *testing.T) {
	/*
	 * qBittorrent rewrites its settings file as the operator changes things in
	 * the UI. Regenerating it on a later run would silently discard all of that —
	 * and the operator would have no reason to suspect the installer.
	 */
	dir := t.TempDir()
	w := &Writer{Dir: dir}
	f := File{Name: EngineConfigFileName, Mode: ModeSecret, Content: "seeded\n", Once: true}
	if _, err := w.Write(f); err != nil {
		t.Fatal(err)
	}
	// Stand in for the engine having rewritten its own settings.
	path := filepath.Join(dir, EngineConfigFileName)
	if err := os.WriteFile(path, []byte("the operator's settings\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	f.Content = "freshly generated\n"
	actions, err := w.Write(f)
	if err != nil {
		t.Fatal(err)
	}
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(content) != "the operator's settings\n" {
		t.Errorf("a write-once file was replaced: %q", content)
	}
	if len(actions) != 1 || actions[0].Kind != "unchanged" {
		t.Errorf("expected it to be left alone, got %v", actions)
	}
}

func TestNestedFilesGetTheirDirectory(t *testing.T) {
	// The engine's config sits two levels down and neither level exists on a
	// first run.
	dir := t.TempDir()
	w := &Writer{Dir: dir}
	if _, err := w.Write(File{Name: EngineConfigFileName, Mode: ModeSecret, Content: "x\n"}); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, EngineConfigFileName)); err != nil {
		t.Errorf("nested file was not created: %v", err)
	}
}

func TestEngineConfigVolumeIsBoundSoItCanBeSeeded(t *testing.T) {
	/*
	 * A named volume cannot be written to until something mounts it, so with the
	 * Compose default the only way to set a password is the one the file
	 * documents: read the temporary one out of the log. Binding it is what makes
	 * seeding possible at all.
	 */
	p, _ := qbPlan()
	override := RenderOverride(p)
	if !strings.Contains(override, "qbittorrent_config:") {
		t.Fatalf("the engine's config volume should be bound:\n%s", override)
	}
	if !strings.Contains(override, filepath.Join(p.InstallDirectory, EngineConfigDirName)) {
		t.Errorf("it should bind to the installation directory:\n%s", override)
	}

	p.Torrent.Engine = plan.EngineRtorrent
	p.Finalize()
	if strings.Contains(RenderOverride(p), "qbittorrent_config") {
		t.Error("no qBittorrent, no qBittorrent config volume")
	}
}

// --- optional services -----------------------------------------------------

func fileNamed(files []File, name string) *File {
	for i := range files {
		if files[i].Name == name {
			return &files[i]
		}
	}
	return nil
}

func TestProwlarrsKeyIsSeededSoTheIntegrationCanBeWired(t *testing.T) {
	/*
	 * Without seeding, the key is generated inside the container and the only way
	 * to wire Prowlarr into UltraTorrent is to ask the operator to copy it out of
	 * a web UI. With it, both that link and the FlareSolverr indexer proxy are
	 * reachable through Prowlarr's own API — verified against Prowlarr 2.4.0,
	 * where a seeded key is preserved and accepted immediately.
	 */
	p, s := qbPlan()
	p.Companions.Prowlarr = true
	p.Finalize()
	s.ProwlarrAPIKey = "0123456789abcdef0123456789abcdef"

	config := fileNamed(Render(p, s), ProwlarrConfigFileName)
	if config == nil {
		t.Fatal("no Prowlarr config was generated")
	}
	if !strings.Contains(config.Content, s.ProwlarrAPIKey) {
		t.Error("the seeded key is missing")
	}
	if config.Mode != ModeSecret {
		t.Errorf("mode = %#o — the key grants full control of the indexer manager", config.Mode)
	}
	if !config.Once {
		t.Error("Prowlarr rewrites this file itself")
	}
}

func TestNoProwlarrConfigWithoutProwlarr(t *testing.T) {
	p, s := qbPlan()
	p.Companions.Prowlarr = false
	p.Finalize()
	if fileNamed(Render(p, s), ProwlarrConfigFileName) != nil {
		t.Error("a config was generated for a companion that is not deployed")
	}
}

func TestProwlarrsUIIsUnpublishedByDefault(t *testing.T) {
	/*
	 * `!reset` rather than an empty list: a `ports:` entry in an override is
	 * APPENDED to the base one, so `ports: []` would leave the original mapping
	 * in place and quietly do nothing — verified against Compose, where a plain
	 * override produced two mappings for the same host port.
	 */
	p, _ := qbPlan()
	p.Companions.Prowlarr = true
	p.Companions.PublishProwlarrUI = false
	p.Finalize()

	override := RenderOverride(p)
	if !strings.Contains(override, "ports: !reset []") {
		t.Errorf("the published port should be reset, not appended to:\n%s", override)
	}

	p.Companions.PublishProwlarrUI = true
	p.Finalize()
	if strings.Contains(RenderOverride(p), "prowlarr:\n    ports: !reset") {
		t.Error("an explicitly published UI must stay published")
	}
}

func TestTheBundledProxyUsesAGeneratedCaddyfile(t *testing.T) {
	/*
	 * deploy/Caddyfile is tracked in the repository and mounted read-only, and is
	 * hardcoded to :80. Editing it would fork the installation from the project
	 * the first time upstream changed it — the same reason docker-compose.yml is
	 * never generated — so the mount is redirected instead.
	 */
	p, s := qbPlan()
	p.Networking.UseBundledProxy = true
	p.Networking.PublicURL = "https://media.example.com"
	p.Finalize()

	if fileNamed(Render(p, s), proxy.CaddyfileName) == nil {
		t.Fatal("no Caddyfile was generated")
	}
	override := RenderOverride(p)
	if !strings.Contains(override, "/etc/caddy/Caddyfile:ro") {
		t.Errorf("the proxy should mount the generated file:\n%s", override)
	}
	if !strings.Contains(override, filepath.Join(p.InstallDirectory, proxy.CaddyfileName)) {
		t.Error("it should mount the file from the installation directory")
	}
}

func TestNoCaddyfileWithoutTheBundledProxy(t *testing.T) {
	// An operator already behind their own proxy must not get a second one, nor
	// a stray config file suggesting they have.
	p, s := qbPlan()
	p.Networking.UseBundledProxy = false
	p.Networking.BehindReverseProxy = true
	p.Finalize()
	if fileNamed(Render(p, s), proxy.CaddyfileName) != nil {
		t.Error("a Caddyfile was generated for an installation that deploys no proxy")
	}
}

// TestGenerationRefusesAWindowsTargetForNow pins an honest limitation.
//
// A Windows plan is a valid document and validates fine — but every volume this
// generator writes binds a host path through Docker's local driver, which is a
// Linux mount performed inside the Docker VM. Writing that YAML for a Windows
// host would produce a stack that starts and silently stores everything
// somewhere the operator never named, which is worse than any error.
func TestGenerationRefusesAWindowsTargetForNow(t *testing.T) {
	p := plan.RecommendedFor("test", plan.TargetWindows)
	p.Finalize()

	err := CheckTarget(p)
	if err == nil {
		t.Fatal("generating for a Windows target must refuse until the volume form is settled")
	}
	if !errors.Is(err, ErrTargetNotImplemented) {
		t.Errorf("callers need to recognise this: %v", err)
	}
	// The message has to name the reason and where it is tracked, or the next
	// person reads it as "Windows is not supported" and stops.
	for _, want := range []string{"plan a Windows installation", "Docker Desktop", "W3"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("message should mention %q: %v", want, err)
		}
	}

	// A Linux plan is unaffected.
	if err := CheckTarget(plan.Recommended("test")); err != nil {
		t.Errorf("a Linux target must still generate: %v", err)
	}
}
