// Package config renders and writes the files an installation needs.
//
// Rendering is pure: it takes a plan plus secrets and returns file contents.
// Writing is separate and does the careful parts — permissions before content,
// atomic replace, timestamped backups. Splitting them means every question about
// "what does this deployment actually get" is a string comparison in a test,
// with no filesystem involved.
//
// What is generated, and what deliberately is not:
//
//   - `.env` — every value the Compose stack reads. Generated.
//   - `docker-compose.override.yml` — only where the plan needs to specialise
//     the canonical stack. Generated.
//   - `installer-state.json` — non-secret metadata for status, doctor and
//     reconfigure. Generated.
//   - `docker-compose.yml` — NEVER. The repository's file is canonical; a
//     generated copy would fork the deployment from the project the first time
//     the upstream file changed.
package config

import (
	"bufio"
	"fmt"
	"sort"
	"strings"

	"github.com/ultratorrent/installer/internal/plan"
)

// Header marks every generated file.
//
// States the two things a person who finds this file needs: what wrote it, and
// that editing it by hand is not durable.
func Header(installerVersion, when string) string {
	return fmt.Sprintf(`# Generated by the UltraTorrent Installer
# Installer version: %s
# Generated: %s
#
# Manual edits may be overwritten by `+"`ultratorrent-install reconfigure`"+`.
# A timestamped backup is taken before this file is replaced.
`, installerVersion, when)
}

// RenderEnv produces the .env contents.
//
// Values are grouped and commented the way `.env.example` is, because an
// operator who opens this file has almost certainly read that one, and a
// familiar shape is worth more than a compact one.
func RenderEnv(p *plan.Plan, s *plan.Secrets) string {
	var b strings.Builder
	b.WriteString(Header(p.InstallerVersion, p.CreatedAt.Format("2006-01-02 15:04:05 MST")))

	section := func(title string) {
		b.WriteString("\n# " + strings.Repeat("-", 72) + "\n# " + title + "\n# " +
			strings.Repeat("-", 72) + "\n")
	}
	set := func(key, value string) { fmt.Fprintf(&b, "%s=%s\n", key, value) }
	comment := func(lines ...string) {
		for _, l := range lines {
			b.WriteString("# " + l + "\n")
		}
	}

	section("Web UI")
	comment("The only port published by the core stack. The backend is not",
		"published; the frontend proxies /api and /ws to it internally.")
	set("FRONTEND_PORT", itoa(p.Networking.FrontendPort))
	comment("Origins the backend will accept browser requests from.")
	set("CORS_ORIGIN", corsOrigin(p))

	section("Database (internal only — never published to the host)")
	comment("Compose DERIVES DATABASE_URL from these three values, so the",
		"password must stay alphanumeric: a URL-special character would",
		"corrupt the derived URL and fail as an authentication error.")
	set("POSTGRES_USER", p.Database.User)
	set("POSTGRES_DB", p.Database.Name)
	set("POSTGRES_PASSWORD", s.PostgresPassword)

	section("Cache (internal only)")
	set("REDIS_HOST", p.Redis.Host)
	set("REDIS_PORT", itoa(p.Redis.Port))

	section("Secrets — required, and validated by the backend at boot")
	comment("Each is at least 32 characters and mutually distinct; the backend",
		"refuses to start otherwise. Changing ENCRYPTION_KEY invalidates every",
		"stored two-factor secret.")
	set("JWT_ACCESS_SECRET", s.JWTAccessSecret)
	set("JWT_REFRESH_SECRET", s.JWTRefreshSecret)
	set("ENCRYPTION_KEY", s.EncryptionKey)

	section("Initial administrator (used once, by the first seed)")
	set("ADMIN_USERNAME", p.Admin.Username)
	set("ADMIN_EMAIL", p.Admin.Email)
	set("ADMIN_PASSWORD", s.AdminPassword)

	section("Storage")
	comment("Absolute roots the file manager may browse, inside the containers.")
	set("FILE_MANAGER_ROOTS", "/downloads")

	if profiles := p.ComposeProfiles(); len(profiles) > 0 {
		section("Compose profiles")
		comment("Docker does NOT remember --profile between commands: a later",
			"`docker compose up -d` without them STOPS the profiled services.",
			"Setting it here makes every plain compose command in this directory",
			"bring up the same stack the installer deployed.")
		set("COMPOSE_PROFILES", strings.Join(profiles, ","))
	}

	if p.Torrent.Engine == plan.EngineQbittorrent {
		section("Bundled qBittorrent")
		set("QBITTORRENT_PORT", itoa(p.Torrent.WebUIPort))
	}
	if p.Torrent.Engine == plan.EngineRtorrent {
		section("Bundled rTorrent")
		comment("DHT is off by default: this build can crash on a DHT",
			"internal_error. Trackers and PEX still find peers.")
		set("RT_DHT", map[bool]string{true: "on", false: "off"}[p.Torrent.EnableDHT])
	}
	if p.Torrent.PUID > 0 || p.Torrent.PGID > 0 {
		comment("", "Downloads are written as this user/group. Set to the owner of your",
			"media directory so files land with the right ownership.")
		set("PUID", itoa(p.Torrent.PUID))
		set("PGID", itoa(p.Torrent.PGID))
	}

	if p.Companions.Prowlarr {
		section("Prowlarr companion")
		set("PROWLARR_PORT", itoa(p.Companions.ProwlarrPort))
		/*
		 * PROWLARR_BASE_URL is deliberately NOT written.
		 *
		 * The backend reads it, but docker-compose.yml does not pass it into the
		 * backend container, so a value here would reach nothing. Writing it
		 * anyway would be worse than useless: an operator editing it to point at
		 * a different Prowlarr would see no effect and no error. The backend's
		 * own default is http://prowlarr:9696 — the bundled companion — which is
		 * exactly what this deployment runs.
		 */
		/*
		 * SSRF_ALLOW_HOSTS is deliberately NOT written here.
		 *
		 * docker-compose.yml already defaults it to `prowlarr`, which is what
		 * lets the bundled indexer's private-IP .torrent links past the SSRF
		 * guard. Writing our own copy would freeze today's default into this
		 * file and silently diverge if the platform ever widens it — and getting
		 * it wrong is invisible: auto-downloads fail with a blocked-address
		 * error while every container looks healthy.
		 */
		comment("", "SSRF_ALLOW_HOSTS is intentionally not set: the Compose file already",
			"defaults it to `prowlarr`, which is what allows the bundled indexer's",
			"private-address torrent links. Add your own indexer host here only if",
			"you have one, and KEEP `prowlarr` in the list:",
			"  SSRF_ALLOW_HOSTS=prowlarr,indexer.lan")
	} else if _, write := p.SSRFAllowHosts(); write {
		section("SSRF protection")
		comment("No bundled indexer, so the guard stays at full strength. An empty",
			"value is explicit: leaving it unset would inherit the Compose default,",
			"which trusts a `prowlarr` host this deployment does not run.")
		set("SSRF_ALLOW_HOSTS", "")
	}

	return b.String()
}

// corsOrigin decides what the backend will accept browser requests from.
//
// The public URL when the operator gave one, because that is what a browser
// actually sends. Otherwise the frontend's own published port on localhost,
// which matches the Compose default and works for the first sign-in.
func corsOrigin(p *plan.Plan) string {
	if p.Networking.PublicURL != "" {
		return p.Networking.PublicURL
	}
	return fmt.Sprintf("http://localhost:%d", p.Networking.FrontendPort)
}

// ParseEnv reads a .env file into key/value pairs.
//
// Used to preserve an existing installation's secrets on re-run. Deliberately
// forgiving about what it does not understand — this file may have been edited
// by hand, and an unparsable line is not a reason to refuse to read the rest.
func ParseEnv(content string) map[string]string {
	values := map[string]string{}
	scanner := bufio.NewScanner(strings.NewReader(content))
	// A generated .env is small, but a hand-edited one may have long lines.
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		line = strings.TrimPrefix(line, "export ")
		key, value, found := strings.Cut(line, "=")
		if !found {
			continue
		}
		key = strings.TrimSpace(key)
		value = strings.TrimSpace(value)
		if len(value) >= 2 {
			if (value[0] == '"' && value[len(value)-1] == '"') ||
				(value[0] == '\'' && value[len(value)-1] == '\'') {
				value = value[1 : len(value)-1]
			}
		}
		values[key] = value
	}
	return values
}

// ExistingSecrets recovers the secrets already in use at an installation.
//
// This is what makes a re-run safe. Regenerating secrets against a live
// deployment is catastrophic in a quiet way: the database password stops
// matching the volume that already exists, every session is invalidated, and
// ENCRYPTION_KEY changing makes every stored two-factor secret undecryptable.
// So a re-run reads what is there and keeps it.
//
// Returns nil when the file holds no usable secrets, which is the signal to
// generate a fresh set.
func ExistingSecrets(envContent string) *plan.Secrets {
	values := ParseEnv(envContent)
	s := &plan.Secrets{
		PostgresPassword: values["POSTGRES_PASSWORD"],
		JWTAccessSecret:  values["JWT_ACCESS_SECRET"],
		JWTRefreshSecret: values["JWT_REFRESH_SECRET"],
		EncryptionKey:    values["ENCRYPTION_KEY"],
		AdminPassword:    values["ADMIN_PASSWORD"],
	}
	// "Usable" means the signing keys are present. A missing ADMIN_PASSWORD is
	// survivable — the admin already exists in the database by then — but a
	// missing JWT secret means this was never a working installation.
	if s.JWTAccessSecret == "" || s.EncryptionKey == "" || s.PostgresPassword == "" {
		return nil
	}
	return s
}

// EnvKeys lists the keys a rendered env sets, sorted. For tests and for doctor,
// which reports on required variables without ever printing their values.
func EnvKeys(content string) []string {
	keys := make([]string, 0, 24)
	for k := range ParseEnv(content) {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func itoa(n int) string { return fmt.Sprintf("%d", n) }
