// Package proxy generates the bundled reverse proxy's configuration.
//
// The repository already ships one — `profiles: ["proxy"]`, Caddy — so the
// installer configures that rather than adding a second. Two proxies in front of
// one application is the kind of thing that works until a WebSocket upgrade or a
// forwarded header quietly stops matching.
//
// What the installer must NOT do is edit `deploy/Caddyfile`. It is tracked in the
// repository and mounted read-only, so an installation that changed it would
// fork from the project the first time upstream touched it — the same reason
// docker-compose.yml is never generated. The generated file lives in the
// installation directory and the mount is redirected to it.
package proxy

import (
	"fmt"
	"net/url"
	"strings"
)

// CaddyfileName is the generated file's name in the installation directory.
const CaddyfileName = "Caddyfile"

// Settings describe the site the proxy serves.
type Settings struct {
	// PublicURL is what users type. A hostname over https gets an automatic
	// certificate; anything else is served on :80.
	PublicURL string
	// BackendService and FrontendService are the internal Compose addresses.
	BackendService  string
	FrontendService string
}

// SiteAddress turns the public URL into Caddy's site address.
//
// The distinction decides whether Caddy tries to obtain a certificate at all. A
// bare `:80` means it does not, which is right for an IP address or localhost —
// Let's Encrypt will not issue for either, and Caddy retrying a hopeless
// challenge is a startup that never settles.
func SiteAddress(publicURL string) (address string, automaticHTTPS bool) {
	if publicURL == "" {
		return ":80", false
	}
	parsed, err := url.Parse(publicURL)
	if err != nil || parsed.Host == "" {
		return ":80", false
	}
	host := parsed.Hostname()
	if host == "" || isIPish(host) || host == "localhost" {
		return ":80", false
	}
	if parsed.Scheme == "http" {
		// An explicit http:// URL is a deliberate choice; serving it over TLS
		// anyway would break the address the operator told us people use.
		return "http://" + host, false
	}
	return host, true
}

// RenderCaddyfile produces the proxy configuration.
//
// The routing mirrors the repository's own Caddyfile exactly — /api and /ws to
// the backend, everything else to the frontend — because that split is the
// application's, not the proxy's, and inventing a different one here would make
// the bundled proxy behave unlike the documented one.
func RenderCaddyfile(s Settings) string {
	address, automaticHTTPS := SiteAddress(s.PublicURL)
	backend := s.BackendService
	if backend == "" {
		backend = "backend:4000"
	}
	frontend := s.FrontendService
	if frontend == "" {
		frontend = "frontend:8080"
	}

	var b strings.Builder
	b.WriteString("# Generated by the UltraTorrent Installer.\n")
	b.WriteString("#\n")
	b.WriteString("# The repository's own deploy/Caddyfile is left untouched; the Compose\n")
	b.WriteString("# override points the proxy at this file instead.\n")
	if automaticHTTPS {
		b.WriteString("#\n")
		b.WriteString("# Caddy will obtain and renew a certificate for this name automatically.\n")
		b.WriteString("# That needs port 80 reachable from the internet and the name already\n")
		b.WriteString("# resolving to this host — otherwise the first start will keep retrying.\n")
	} else {
		b.WriteString("#\n")
		b.WriteString("# Served over plain HTTP: an automatic certificate needs a domain name,\n")
		b.WriteString("# and no certificate authority will issue one for an IP or localhost.\n")
	}
	fmt.Fprintf(&b, "\n%s {\n", address)
	b.WriteString("\tencode gzip\n\n")
	b.WriteString("\t# API and WebSocket traffic to the backend.\n")
	b.WriteString("\t@api path /api/* /ws/*\n")
	b.WriteString("\thandle @api {\n")
	fmt.Fprintf(&b, "\t\treverse_proxy %s\n", backend)
	b.WriteString("\t}\n\n")
	b.WriteString("\t# Everything else to the static frontend. Its nginx runs unprivileged\n")
	b.WriteString("\t# and listens on 8080, not 80.\n")
	b.WriteString("\thandle {\n")
	fmt.Fprintf(&b, "\t\treverse_proxy %s\n", frontend)
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String()
}

// isIPish reports whether a host looks like a literal address rather than a name.
func isIPish(host string) bool {
	if strings.Contains(host, ":") {
		return true // an IPv6 literal
	}
	if host == "" {
		return false
	}
	for _, r := range host {
		if (r < '0' || r > '9') && r != '.' {
			return false
		}
	}
	return true
}
