import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Six sidebars, one per audience-journey. Each is **autogenerated** from the
 * folder tree, so adding a page is just adding a file — the sidebar, breadcrumbs
 * and next/prev links follow automatically and can never dangle.
 *
 * Ordering inside a folder comes from each page's `sidebar_position` front-matter;
 * each folder's label/description comes from its `_category_.json`.
 */
const sidebars: SidebarsConfig = {
  // Understand it, then use it.
  learn: [{ type: 'autogenerated', dirName: 'learn' }],

  // Get it running, anywhere.
  install: [{ type: 'autogenerated', dirName: 'install' }],

  // One section per functional module.
  modules: [{ type: 'autogenerated', dirName: 'modules' }],

  // Machine-generated from source — never hand-edited, so it cannot drift.
  reference: [{ type: 'autogenerated', dirName: 'reference' }],

  // Extend and contribute.
  develop: [{ type: 'autogenerated', dirName: 'develop' }],

  // Run it in production: troubleshoot, secure, back up, tune.
  operate: [{ type: 'autogenerated', dirName: 'operate' }],

  // FAQ + glossary (linked from the footer).
  help: [{ type: 'autogenerated', dirName: 'help' }],
};

export default sidebars;
