// Package companion configures the optional services that ship alongside
// UltraTorrent but are not part of it.
//
// The one thing that matters here is Prowlarr's API key. It is generated on
// first start and lives in the container's config, which means an installer that
// does not seed it cannot wire the integration afterwards without asking the
// operator to copy a key out of a web UI. Seeding it makes the whole
// Prowlarr-to-UltraTorrent link automatable — and, separately, lets the
// installer add FlareSolverr as an indexer proxy through Prowlarr's own API
// instead of documenting the click path.
package companion

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"strings"
)

// ProwlarrConfigPath is the settings file inside Prowlarr's config volume.
const ProwlarrConfigPath = "config.xml"

// APIKeyLength is Prowlarr's own: 32 hex characters.
const APIKeyLength = 16 // bytes, rendered as 32 hex characters

// NewAPIKey generates a key in the shape Prowlarr uses.
//
// Verified against Prowlarr 2.4.0: a key written into config.xml before first
// start is kept, is accepted on `X-Api-Key` immediately, and a wrong key is
// rejected with 401.
func NewAPIKey() (string, error) {
	raw := make([]byte, APIKeyLength)
	if _, err := rand.Read(raw); err != nil {
		return "", fmt.Errorf("generating a Prowlarr API key: %w", err)
	}
	return hex.EncodeToString(raw), nil
}

// ProwlarrSettings is what the installer decides about the bundled Prowlarr.
type ProwlarrSettings struct {
	APIKey string
	// Port is the port INSIDE the container. Prowlarr does not check the Host
	// header the way qBittorrent does, so a published port that differs is fine.
	Port int
	// PublishUI reflects whether the operator asked for the Web UI on the host.
	//
	// It changes nothing in the file. It is here because the security note that
	// belongs in the file depends on it, and because a reader of this struct
	// should see that the decision was considered rather than overlooked.
	PublishUI bool
}

// RenderProwlarrConfig produces config.xml.
//
// Deliberately minimal. Prowlarr fills in everything it needs on first start and
// preserves what it was given, so the installer writes only what it has a reason
// to decide — a longer file would be a set of defaults to drift from Prowlarr's
// own without ever being noticed.
//
// # Authentication is deliberately NOT configured here
//
// Measured against Prowlarr 2.4.0, and the result is the reason the installer
// leaves the Web UI unpublished by default:
//
//   - `AuthenticationRequired=DisabledForLocalAddresses` serves the application
//     unauthenticated through a PUBLISHED port. Every request arriving that way
//     comes from the Docker gateway, which is a private address, so "local" means
//     anyone who can reach the host.
//   - `Enabled` with `Forms` redirects to a login page that offers no way to
//     create an account, and Prowlarr keeps its users in its own SQLite database
//     rather than in this file. Seeding one would mean writing directly into
//     another application's tables, which is not something an installer should do.
//     The result is a lockout.
//   - Writing no authentication settings at all leaves the UI open, and Prowlarr
//     does not force a setup wizard.
//
// So there is no setting that is both safe and usable for a published UI. The
// installer keeps the UI on the internal network, where the API key is the only
// credential that matters, and says plainly what to do if the operator publishes
// it anyway.
func RenderProwlarrConfig(s ProwlarrSettings) string {
	var b strings.Builder
	b.WriteString(`<?xml version="1.0" encoding="utf-8"?>` + "\n")
	b.WriteString("<!--\n")
	b.WriteString("  Generated by the UltraTorrent Installer.\n")
	b.WriteString("  Prowlarr rewrites this file itself; the installer seeds it once and\n")
	b.WriteString("  then leaves it alone.\n")
	if s.PublishUI {
		b.WriteString("\n")
		b.WriteString("  The Web UI is published on the host and Prowlarr starts with NO\n")
		b.WriteString("  authentication. Set it up now in Prowlarr: Settings -> General ->\n")
		b.WriteString("  Security. It is not configured here because the only settings that\n")
		b.WriteString("  enforce authentication also lock you out: Prowlarr keeps its users in\n")
		b.WriteString("  its own database and offers no way to create the first one from the\n")
		b.WriteString("  login page.\n")
	}
	b.WriteString("-->\n")
	b.WriteString("<Config>\n")
	b.WriteString("  <BindAddress>*</BindAddress>\n")
	fmt.Fprintf(&b, "  <Port>%d</Port>\n", s.Port)
	b.WriteString("  <UrlBase></UrlBase>\n")
	// The reason this file is generated at all.
	fmt.Fprintf(&b, "  <ApiKey>%s</ApiKey>\n", s.APIKey)
	b.WriteString("  <LogLevel>info</LogLevel>\n")
	b.WriteString("  <InstanceName>Prowlarr</InstanceName>\n")
	// Prowlarr runs from a container image; its own updater must stay out of it.
	b.WriteString("  <UpdateMechanism>Docker</UpdateMechanism>\n")
	b.WriteString("</Config>\n")
	return b.String()
}

// ParseAPIKey reads the API key out of a Prowlarr config.xml.
//
// Prowlarr owns this file after first start, and the installer's Once rule
// means an existing one is never rewritten. So on any run after the first the
// installer holds NO key of its own — the generated one is not persisted
// anywhere — while Prowlarr holds the one that actually works. Reading it back
// is what lets a later run finish wiring the integration, and it is correct by
// construction: the key that Prowlarr is using is the key that Prowlarr will
// accept, whether the installer seeded it or Prowlarr generated its own.
func ParseAPIKey(xml string) string {
	const open, close = "<ApiKey>", "</ApiKey>"
	start := strings.Index(xml, open)
	if start < 0 {
		return ""
	}
	rest := xml[start+len(open):]
	end := strings.Index(rest, close)
	if end < 0 {
		return ""
	}
	return strings.TrimSpace(rest[:end])
}
